multiply_values = int(input("enter value 1: "))
multiply_values2 = int(input("enter value 2 :"))
multiply_values3 = int(input("enter value 3 :"))
multiply_values4 = int(input("enter value 4 : "))
n = int(input("enter the value of n: "))
geometric_mean = (multiply_values*multiply_values2*multiply_values3*multiply_values4)**(1/n)
print ('The Geometric Mean is: ' ,(geometric_mean))